### ISSUE TITLE
The Terminal should be responsible for handling charset encoding / decoding

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#12]
Usually, I'd think that people use character streams and will read / write from the terminals.  The terminal is the one that has the encoding and it should be responsible for handling it.

The `Terminal` should get back the `Reader` field, which was supporting this.  It should not be done on the  `Connection`.

**Comment by stalep** [comment]
I would argue that the API we have now is better than having a Reader on Terminal. The Terminal is providing input/output/charset and how input is read should not be tied to it.

**Comment by gnodet** [comment]
You can't just choose the encoding of the terminal on the connection.
For example, on OS X, I can change the encoding of the terminals, but i choose it, my applications need to use the correct encoding, else the display is garbaged.

For example if I turn my iTerm encoding into a non utf-8 encoding, I have the following output:
```
gnodetâ€˘~Â» cat /Users/gnodet/work/git/hawtio/hawtio-web/node_modules/grunt/test/fixtures/utf8.txt
AĂ§ĂŁo Ă© isso aĂ­
```

Where as it should be
```
gnodet•~» cat /Users/gnodet/work/git/hawtio/hawtio-web/node_modules/grunt/test/fixtures/utf8.txt
Ação é isso aí
```

This means that the encoding is definitely attached to the terminal.  If your terminal uses a given encoding, you can't just choose to send strings with a different encoding. 
So definitely how the input is read should be tied to the terminal and not to a layer above.
The `input()` and `output()` streams should not really be used.

**Comment by gnodet** [comment]
What was the original problem with the `Reader` ? Why did you remove it in the first place ?

**Comment by gnodet** [comment]
Btw, I don't understand the `how input is read should not be tied to it`.  Currently, you read the input using the InputStream and you decode it and get characters from it.  When you use a Reader, it's the exact same process. So unless there are multiple ways of transforming the byte input stream into a character stream with a given encoding, there's no point in moving this control outside the Terminal.

Also, the Terminal class is now a bit weird.  Once it's built, you have no way to know the encoding, but you also have no way to read characters from it. So it's not usable at all.

**Comment by stalep** [comment]
Yes, i agree that the Terminal class is not a bit weird. Connection have taken over as the API readline talks to. Terminal is more a common interface for local terminal connections.
The main reason to remove reader was that reader could be separated from the terminal impl and be "independant". IMO i felt it was limiting to read one int at a time in addition to readline design where we really do not need a separate non-blocking reader except when reading in a "detached" state eg: redirections/pipe in etc.
Im closing this as a wontfix since i do not see this as something that would benefit readline's design.
- but if you have other arguments im willing to reconsider.
