### ISSUE TITLE
The EventDecoder hard codes the control characters

### ISSUE THREAD

**Issue by gnodet** [aeshell/aesh-readline#14]
It uses hard coded values for signals INT, SUSP and EOF.
Those signals are actually already processed correctly by the `LineDisciplineTerminal#processInputByte` function, according to the terminal settings, so with no hard coded values.
I don't understand why the code is duplicated inside the `EventDecoder`.

**Comment by stalep** [comment]
Hm, that's a good observation. The idea is that EventDecoder will "work" even though eg sun.misc.Signals is not available in addition to work against remote connections.
In regards of LineDisciplineTerminal it is a duplicity there since with ExternalTerminal it will all the input immediately (eg for redirect in) and parse it for any signals. It will not send all that data to Readline at once though so for local terminals we do not need EventDecoder true.
I'm not sure what's the best way of solving this yet. It's an optimization, but not a functional issue atm afaik.

**Comment by stalep** [comment]
forgot to comment the hard coded values of EventDecoder. Yes, atm it uses the hardcoded constructor, it supports variable settings as well so it should be more flexible.

**Comment by gnodet** [comment]
But raising signal should be the responsibility of the terminal, I don't see why you want to raise them externally.  The terminals are configured using the `Attributes` structure and it should respect as much as possible the configuration given there.

Also sun.misc.Signals is only relevant for the system terminal, not for pseudo terminals, whether they are local or remote.  This was controlled by the `nativeSignals` flag on the `TerminalBuilder`.

The problem would only be an optimization problem if it was handled correctly by the `EventDecoder`, but that's not really the case.    Remote connections should use a terminal inheriting `LineDisciplinedTerminal` or `ExternalTerminal`, and that's already the case when using the `TerminalBuilder` to create the terminal, so I still don't understand what problem is solved by the `EventDecoder`.

**Comment by stalep** [comment]
EventDecoder now also reads values from Attributes. This is the default way of setting events on local terminals. The same behavior will attempted on remote shells as well.
